config/routes.rb
DanceSchool::Application.routes.draw do

  resources :pictures
  resources :events
  resources :lessons
  resources :dancers

  devise_for :users
  root "pages#home"

  get "about" => "pages#about"
  get "schedule" => "pages#schedule"

end

app/models/biorain.rb
class Biorain < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :image, presence: true
  validates :description, presence: true
end

app/models/dancer.rb
class Dancer < ActiveRecord::Base
  belongs_to :user
  has_many :lessons

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :pictures
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :dancers

  def repeat!(num_times)
    1.upto(num_times) do |i|
      next_lesson = dup                 # self is a Lesson instance (the first lesson created by controller)
      next_lesson.starts_at + i.weeks   # http://api.rubyonrails.org/classes/Numeric.html gives you .weeks
      next_lesson.ends_at + i.weeks
      next_lesson.save!
    end
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :image, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures
  has_many :dancers
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :first_name
   devise_parameter_sanitizer.for(:sign_up) << :last_name
   devise_parameter_sanitizer.for(:sign_up) << :type
   devise_parameter_sanitizer.for(:sign_up) << :gender
   devise_parameter_sanitizer.for(:account_update) << :first_name
   devise_parameter_sanitizer.for(:account_update) << :last_name
   devise_parameter_sanitizer.for(:account_update) << :type
   devise_parameter_sanitizer.for(:account_update) << :gender
  end
end

app/controllers/dancers_controller.rb
class DancersController < ApplicationController
  before_action :set_dancer, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @dancers = Dancer.all.order("created_at DESC")
  end

  def show
  end

  def new
    @dancer = Dancer.new
  end

  def create
     @dancer = Dancer.new(dancer_params)
    if current_user.admin? && @dancer.save
      redirect_to @dancer, notice: 'Dancer was successfully registered.'
    else
      render action: 'new'
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_dancer
      @dancer = Dancer.find(params[:id])
    end

    def correct_user
      @dancer = current_user.dancers.find_by(id: params[:id])
      redirect_to dancers_path, notice: "Not authorized to edit this dancer" if @dancer.nil?
    end

  def dancer_params
      params.require(:dancer).permit(:first_name, :last_name, :gender, :birthdate, :user_id)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.order('created_at desc')
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if current_user.admin? && @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render action: 'new'
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :location, :description, :user_id)
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @lessons = Lesson.all.order("created_at DESC")
  end

  def new
    @lesson = Lesson.new
  end

  def create
     @lesson = Lesson.new(lesson_params)
    if current_user.admin? && @lesson.save
      redirect_to @lesson, notice: 'Lesson was successfully created.'
    else
      render action: 'new'
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

private
 # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def correct_user
      @lesson = current_user.lessons.find_by(id: params[:id])
      redirect_to lessons_path, notice: "Not authorized to edit this lesson" if @lesson.nil?
    end

  def lesson_params
    params.require(:lesson).permit(:level, :starts_at, :ends_at, :instructor, :location, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pictures = Picture.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 40)
  end

  def show
  end

  def new
    @picture = current_user.pictures.build
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      redirect_to @picture, notice: 'Picture was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to @picture, notice: 'Picture was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def correct_user
      @picture = current_user.pictures.find_by(id: params[:id])
      redirect_to pictures_path, notice: "Not authorized to edit this picture" if @picture.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/biorains/_form.html.erb
<%= form_for @biorain, html: { multipart: true } do |f| %>
  <% if @biorain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@biorain.errors.count, "error") %> prohibited this biorain from being saved:</h2>

      <ul>
      <% @biorain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/dancers/new.html.erb
<%= form_for @dancer, html: { multipart: true } do |f| %>
  <% if @dancer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dancer.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @dancer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1>Dancer Registration</h1>

     <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control", :autofocus => true %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control", :autofocus => true %>
      </div>

      <div class-"form-group">
        <div class="radio-inline">
            <label>
              <input type="radio" name="optionsRadios" id="optionsRadios1" value="Female" checked>
                Female
            </label>
          </div>
          <div class="radio-inline">
            <label>
              <input type="radio" name="optionsRadios" id="optionsRadios2" value="Male">
                Male
            </label>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :birthdate %><br>
        <%= f.text_field :birthdate, :id => "datepicker", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Register", class: "btn btn-primary" %>
      </div>

      <% end %>
    </div>

app/views/events/edit.html.erb
<h1>Hello</h1>

app/views/events/index.html.erb
<div class="center">
  <%= link_to 'Back', new_event_path %>
</div>

 <div>
  <div class="table-responsive">
     <thead>
        <tr>
          <th>Name</th>
          <th>location</th>
          <th>description</th>
        </tr>
      </thead>
       <tbody>
        <% @events.each do |e| %>
          <tr>
            <td><%= e.name %></td>
            <td><%= e.location %></td>
            <td><%= e.description %></td>
          </tr>
        <% end %>
      </tbody>
  </div>
</div>

app/views/events/new.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>

  <% end %>

app/views/events/show.html.erb
<div class="center">
  <%= link_to 'Back', events_path %>
</div>


  <div class="center">
  <%= link_to 'Back', new_event_path %>
</div>

 <div>
  <div class="table-responsive">
     <thead>
        <tr>
          <th>Name</th>
          <th>location</th>
          <th>description</th>
        </tr>
      </thead>
       <tbody>
        <tr>
          <td><%= @event.name %></td>
          <td><%= @event.location %></td>
          <td><%= @event.description %></td>
        </tr>
      </tbody>
  </div>
</div>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container-footer">
    <p>Copyright (c) 2014</p>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Flynn Irish Dance", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
   <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="https://www.facebook.com/flynnirishdance?fref=ts" target="_blank">
          <img src="https://s3.amazonaws.com/danceschool/facebook.png" alt="Facebook"></a>
        </li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Schedule <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Schedule", lessons_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "New lesson", new_lesson_path %></li>
            <% end %>
          </ul>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "All Events", events_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "New Event", new_event_path %></li>
            <% end %>
          </ul>
        </li>
        <li>
          <div class="btn-group">
            <button type="button" class="btn btn-xs btn-info navbar-btn dropdown-toggle" data-toggle="dropdown">
              Pictures <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Pictures", pictures_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to 'New Picture', new_picture_path %></li>
              <% end %>
            </ul>
          </div>
        </li>

        <% if user_signed_in? %>
          <li><%= link_to "Registration", new_dancer_path %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DanceSchool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/lessons/index.html.erb
 <div class="center">
  <%= link_to 'Back', new_lesson_path %>
</div>

  <div class="bs-example">
    <table class="table">
      <caption>2014 Fall Schedule</caption>
      <thead>
        <tr>
          <th>Level</th>
          <th>Starts</th>
          <th>Ends</th>
          <th>Location</th>
          <th>Instructor</th>
        </tr>
      </thead>
      <tbody>
          <% @lessons.each do |l| %>
            <tr>
              <td><%= l.level %></td>
              <td><%= l.starts_at.strftime("%A %l:%M %P") %></td>
              <td><%= l.ends_at.strftime("%l:%M %P") %></td>
              <td><%= l.instructor %></td>
              <td><%= l.location %></td>
            </tr>
          <% end %>
      </tbody>
    </table>
  </div>

app/views/lessons/new.html.erb
<%= form_for @lesson, html: { multipart: true } do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
      <%= f.label :level %><br>
      <%= f.select :level, options_for_select([['Beginner', 1], ['Advanced Beginner/Novice', 2], ['Prize Winners', 3], ['Prize Winners and Open Chanpions', 4], ['Hard Shoe', 5], ['Boys Only', 6], ["U10-11 Ceili's", 7], ['All Levels', 8]]), class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :instructor %><br>
      <%= f.select :instructor, [['Bridget', 1], ['Sean', 2]], class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :location %><br>
      <%= f.select :location, [['Aisling Irish Center', 1], ['Mahopac', 2]], class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :starts %><br>
      <%= f.text_field :starts_at, :id => "datetimepicker", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :ends %><br>
      <%= f.text_field :ends_at, :id => "datetimepicker", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>

  <% end %>

app/views/lessons/show.html.erb
  <div class="center">
  <%= link_to 'Back', new_lesson_path %>
</div>

 <div>
  <div class="table-responsive">
     <thead>
        <tr>
          <th>Level</th>
          <th>Starts</th>
          <th>Ends</th>
          <th>Location</th>
          <th>Instructor</th>
        </tr>
      </thead>
       <tbody>
        <tr>
          <td><%= @lesson.level %></td>
          <td><%= @lesson.starts_at %></td>
          <td><%= @lesson.ends_at %></td>
          <td><%= @lesson.instructor %></td>
          <td><%= @lesson.location %></td>
        </tr>
      </tbody>
  </div>
</div>

app/views/pages/about.html.erb
<body>

  <div class="row">

    <!-- Main Content Section -->
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="large-9 push-3 columns">

      <h3>Bridget Flynn <small>T.C.R.G.</small></h3>

      <p>Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short loin. Venison tail chuck pork chop, andouille ball tip beef ribs flank boudin bacon. Salami andouille pork belly short ribs flank cow. Salami sirloin turkey kielbasa. Sausage venison pork loin leberkas chuck short loin, cow ham prosciutto pastrami jowl. Ham hock jerky tri-tip, fatback hamburger shoulder swine pancetta ground round. Tri-tip prosciutto meatball turkey, brisket spare ribs shankle chuck cow chicken ham hock boudin meatloaf jowl.</p>

    </div>

    <!-- Nav Sidebar -->
    <!-- This is source ordered to be pulled to the left on larger screens -->
    <div class="large-3 pull-9 columns">
      <p><img src="https://s3.amazonaws.com/flynnirishdance/Initial+Picture+Uploads/Bridget_bio.v01.jpg" /></p>
    </div>
  </div>

</body>

app/views/pages/home.html.erb
<section class="block">
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
            <div class="active item">
                <img src="https://s3.amazonaws.com/danceschool/DSC_4897.JPG" alt="Slide1" />
            </div>
            <div class="item">
                <img src="https://s3.amazonaws.com/danceschool/DSC_3851.JPG" alt="Slide2" />
            </div>
            <div class="item">
                <img src="https://s3.amazonaws.com/danceschool/DSC_3806.JPG" alt="Slide3" />
            </div>
        </div>
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>
    </div>
</section>



  <div class="jumbotron center">
     <% if user_signed_in? %>
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>
</div>

app/views/pages/schedule.html.erb
<h1>Fall 2014</h1>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Monday</th>
        <th scope="col">Tuesday</th>
        <th scope="col">Wednesday</th>
        <th scope="col">Thursday</th>
        <th scope="col">Friday</th>
        <th scope="col">Saturday</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Beginner</th>
        <td>4:00-5:00pm</td>
        <td></td>
        <td></td>
        <td>4:00-5:00pm</td>
        <td></td>
        <td>11:00-12:00pm</td>
      </tr>
      <tr>
        <th scope="row">Adv Beg & Novice</th>
        <td>4:30-6:00pm</td>
        <td></td>
        <td></td>
        <td>4:30-6:00pm</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <th scope="row">Prize Winners</th>
        <td>5:00-6:30pm</td>
        <td></td>
        <td></td>
        <td>5:00-6:30pm</td>
        <td></td>
        <td></td>
      </tr>
       <tr>
        <th scope="row">Prelim & Open Champs</th>
        <td>5:30-7:30pm</td>
        <td></td>
        <td></td>
        <td>5:30-7:30pm</td>
        <td></td>
        <td>12:00-2:00pm</td>
      </tr>
       <tr>
        <th scope="row">Hard Shoe</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>4:30-6:00pm</td>
      </tr>
      <tr>
        <th scope="row">All Levels<br>*Mahopac*</th>
        <td></td>
        <td>3:30-5:30pm</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
       <tr>
        <th scope="row">Boys Only u10-11<br>$10 pay as you go</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>3:45-4:15pm</td>
        <td></td>
      </tr>
       <tr>
        <th scope="row">Ceili's u10-11</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>11:00-11:30am</td>
      </tr>
      <tr>
        <th scope="row">Private<br>1hr Lessons</th>
        <td></td>
        <td></td>
        <td>2:30-7:30pm</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/pictures/_form.html.erb
<%= form_for @picture, html: { multipart: true } do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div id="pictures" class="transitions-enabled">
  <% @pictures.each do |picture| %>
    <div class="box box panel panel-default">
      <%= image_tag picture.image.url(:medium) %>
        <div class="panel-body">
          <%= picture.description %><br>
          <p>Added by: <%= picture.user.first_name if picture.user %></p>
          <%= link_to 'Show', picture %>
            <% if picture.user == current_user %>
              <td><%= link_to 'Edit', edit_picture_path(picture) %>
              <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
     </div>
  <% end %>
</div>


<div class="center">
  <%= will_paginate @pictures, renderer: BootstrapPagination::Rails %>
</div>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<div class="center">
  <%= link_to 'Back', pictures_path %>
</div>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @picture.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><%= @picture.description %></p>
        <p>Added by: <strong><%= @picture.user.first_name if @picture.user %></strong></p>

        <% if @picture.user == current_user %>
         <%= link_to 'Edit', edit_picture_path(@picture) %>
        <% end %>
      </div>
    </div>
  </div>
</div>